version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend/novabank-api"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "build"
      include: "scope"
    assignees:
      - "hardyrany"
